### ISSUE TITLE
Website Backend api for the login system

### ISSUE THREAD

**Issue by Spira2025** [susyabashti/Login-System-API#1]
Hello,

do you have a example of website backend api?

**Comment by Soyrce** [comment]
All files were connected to the 4Honor owner's server, so all examples were closed

**Comment by Spira2025** [comment]
when i compile the file, the plugin doesn't let me to register on the server, do yo know what's happening?
![image](https://user-images.githubusercontent.com/16746293/79088806-66bc1000-7d09-11ea-877c-bf6ce9b84dda.png)

**Comment by Spira2025** [comment]
> when i compile the file, the plugin doesn't let me to register on the server, do yo know what's happening?
> ![image](https://user-images.githubusercontent.com/16746293/79088806-66bc1000-7d09-11ea-877c-bf6ce9b84dda.png)

Now its working but when i use with MySQL and do the first register SQL the server crash.

**Comment by Spira2025** [comment]
L 04/13/2020 - 00:51:11: Start of error session.
L 04/13/2020 - 00:51:11: Info (map "de_dust2") (file "addons/amxmodx/logs/error_20200413.log")
L 04/13/2020 - 00:51:11: [AMXX] Plugin ("LoginAPI.amxx") is setting itself as failed.
L 04/13/2020 - 00:51:11: [AMXX] Run time error 1 (plugin "LoginAPI.amxx") - forced exit
L 04/13/2020 - 01:18:10: Start of error session.
L 04/13/2020 - 01:18:10: Info (map "de_dust2") (file "addons/amxmodx/logs/error_20200413.log")
L 04/13/2020 - 01:18:10: [AMXX] Plugin file open error (plugin "LoginAPI.amxx")

**Comment by Soyrce** [comment]
> L 04/13/2020 - 00:51:11: Start of error session.
> L 04/13/2020 - 00:51:11: Info (map "de_dust2") (file "addons/amxmodx/logs/error_20200413.log")
> L 04/13/2020 - 00:51:11: [AMXX] Plugin ("LoginAPI.amxx") is setting itself as failed.
> L 04/13/2020 - 00:51:11: [AMXX] Run time error 1 (plugin "LoginAPI.amxx") - forced exit
> L 04/13/2020 - 01:18:10: Start of error session.
> L 04/13/2020 - 01:18:10: Info (map "de_dust2") (file "addons/amxmodx/logs/error_20200413.log")
> L 04/13/2020 - 01:18:10: [AMXX] Plugin file open error (plugin "LoginAPI.amxx")

Make sure you running sql in your server

**Comment by Spira2025** [comment]
Yes SQL is running, 

SELECT * FROM `registros`
STEAM_0:1:53639911	321321	127.0.0.1	hidden@hotmail.com	

When the first register is done, the server doesn't want to turn on. it crash again and again, but if i remove that first entry of the database the server star running whitout shutdowns.

**Comment by Spira2025** [comment]
amx_plugins
Currently loaded plugins:
       name                    version     author            file             status
 [  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running
 [  3] Admin Help              1.8.2       AMXX Dev Team     adminhelp.amxx   running
 [  4] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running
 [  5] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running
 [  6] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running
 [  7] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running
 [  8] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running
 [  9] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running
 [ 10] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running
 [ 11] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running
 [ 12] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running
 [ 13] Scrolling Message       1.8.2       AMXX Dev Team     scrollmsg.amxx   running
 [ 14] Info. Messages          1.8.2       AMXX Dev Team     imessage.amxx    running
 [ 15] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running
 [ 16] NextMap                 1.8.2       AMXX Dev Team     nextmap.amxx     running
 [ 17] Nextmap Chooser         1.8.2       AMXX Dev Team     mapchooser.amxx  running
 [ 18] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running
 [ 19] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running
 [ 20] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running
 [ 21] StatsX                  1.8.2       AMXX Dev Team     statsx.amxx      running
 [ 22] Login System            0.4         SUSYABASHTI       LoginAPI.amxx    debug
22 plugins, 22 running

Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.8.2    ini  Start ANY
 [ 2] MySQL            RUN   -    mysql_amxx.dll    v1.8.2    pl1  ANY   ANY
 [ 3] Fun              RUN   -    fun_amxx.dll      v1.8.2    pl1  ANY   ANY
 [ 4] CStrike          RUN   -    cstrike_amxx.dll  v1.8.2    pl1  ANY   ANY
 [ 5] CSX              RUN   -    csx_amxx.dll      v1.8.2    pl1  ANY   ANY
5 plugins, 5 running

i remove the first entry STEAM_0:1:53639911 from the database and now is running but if i do the register from the server stars to crash.

**Comment by susyabashti** [comment]
Hmm, i'll check on that. Been inactive for long😑

**Comment by susyabashti** [comment]
After looking at the code, i noticed a missing function, i'll update the function once im on my computer and check if it fixes the problem
